### ISSUE TITLE
go-james clean removes complete project directory

### ISSUE THREAD

**Issue by shizonic** [pieterclaerhout/go-james#81]
If I run `go-james clean` the whole directory (e.g. `/home/tm/code/github/shizonic/go-web`) gets removed instead of only the build folder inside.

**Comment by pieterclaerhout** [comment]
Is that with the latest commit?

Can you check your `go-james.json` file? The property "output" under "build" was incorrectly named "ouput". I've fixed this in https://github.com/pieterclaerhout/go-james/commit/727fad5560c4a61cfa57609baf7d1b3304f6a539, so you might need to update your `go-james.json` file.

**Comment by pieterclaerhout** [comment]
In the meantime, I've added some checks to prevent this from happening in the first place…

**Comment by shizonic** [comment]
Thanks for the quick reply. I just wanted to make a PR because of multiple typos, but you fixed it before.

Guess go-james clean is now fixed too. Thanks for the hotfix. :)
